### ISSUE TITLE
Localization support in the XSL stylesheet

### ISSUE THREAD

**Issue by lexjansen** [lexjansen/define-xml-2.0-stylesheets#2]
Constant text like columns names, captions, ... are in English. There should be localization support. One idea is to have the localization in include files.

**Comment by DmitryMK** [comment]
May be it will be better just to solve it using <xsl:choose> and create a parameter **interfaceLang**? I don't think that there are too many places where the translation is needed. Potentially this could be done using one of many available i18n JS libraries, but it does not look like a good solution within XSLT.

**Comment by lexjansen** [comment]
There are 2 kinds of localizations. One is in the Define-XML document, but the other one is in the XSLT itself, where things like display labels (For example "Datasets") and rendered HTML table columns ("Dataset", "Description", Class", ...) will need to be translated.
For the XML a parameter will work, since all the translations are in the XML file. For the second case there need to be translation in the XSLT file itself, or better, through an included file, for example "define2-0_zh.xsl".
![2020-07-13_16-32-24](https://user-images.githubusercontent.com/11705643/87351035-c6070780-c526-11ea-90ec-be901a8a0705.png)

**Comment by DmitryMK** [comment]
I understand that we are speaking about an interface language. My idea is that it can be done within the same XSLT by using something like 

```
<li class="hmenu-submenu">
   <span class="hmenu-bullet" onclick="toggle_submenu(this);">+</span>
   <a class="tocItem" href="#datasets">
       <xsl:choose>
           <xsl:when test="$interfaceLang = 'en'">
               <xsl:text>Dataset</xsl:text>
           </xsl:when>
           <xsl:when test="$interfaceLang = 'jp'">
               <xsl:text>データセット</xsl:text>
           </xsl:when>
           <xsl:when test="$interfaceLang = 'ch'">
               <xsl:text>资料集</xsl:text>
           </xsl:when>
       </xsl:choose>
   </a>
   ...
```
The benefit of this approach is that it is easier to support a single file, rather than a set of files.

**Comment by lexjansen** [comment]
Yes, but than you need to update the main stylesheet every time there is a language update.

**Comment by lexjansen** [comment]
Also, we should really get to HTML renditions to be submitted, instead of submitting XML + XSLT. You really should not have to update the stylesheet to get a different default value.

**Comment by lexjansen** [comment]
I have a working concept for the localization of the interface language. There will be indeed be a parameter called interfaceLang. For example for Chinese, interfaceLang="zh".
Also, there will be a dictionary file "dictionary.xml" in the same folder as the stylesheet.
This dictionary file will contain translations:

```
<?xml version="1.0" encoding="utf-8"?>
<dictionary>
  <entry term="Datasets">
    <TranslatedText xml:lang="zh">数据集</TranslatedText>
    <TranslatedText xml:lang="jp">データセット</TranslatedText>
  </entry>
```
This dictionary file contains an <entry> element for every term that needs to be translated.

In the XSL, instead of hard-coding a term like "Datasets" we will have a template call like:
```
  <xsl:call-template name="lookupTerm">
     <xsl:with-param name="term" select="'Datasets'" />
   </xsl:call-template>  
```

This template will use the $interfaceLang variable to lookup the correct translation.
In case the dictionary file or the lookup term can not be found, the lookup term will be used, for example "Datasets".
This means that the default is English. 

I feel that this is a good solution, but I appreciate feedback. The good thing is that the style sheet will not have to be updated when translations are added or are changed.

**Comment by DmitryMK** [comment]
Lex, this looks logical from the programming point of view and I like the approach. With a separate file, it is possible just to update translation and keep the main stylesheet intact. Still I have two concerns:
1) From the user point of view it will be less convenient than having a single file, plus if files are updated separately we will end up with people using different translations.
2) I'm also not 100% sure browsers will easily allow to load a separate XML file, this does not look safe from the browser point of view.

Possible ideas:
* Keep the translation data within the stylesheet and then use it for the lookupTerm (which still has the problem that translation update requires the stylesheet update).
* Have a default translation data in the stylesheet as above, but if a user put dictionary.xml in the same folder, it will be used instead.

**Comment by lexjansen** [comment]
Thanks, Dmitry. 
The first idea is certainly possible. 
The second idea is already implemented. When I do a lookup for a term, and that term can not be found - whether or not the dictionary file is there - the term will be used. 

Also, I really think we should get away from the browser loading the XSL, but instead create and send the HTML file together with the Define-XML file. Then you will have a single HTML file. Also, If you want to use a parameter, you need to use an XSLT processor other then the browser. 

Since the stylesheet is not standard, nothing would stop a user to edit the translations even if they are in the stylesheet itself.

**Comment by DmitryMK** [comment]
Lex, sorry I missed that the term will be used by default if the dictionary is not found, that looks good. So for English people can still use just XSLT and for other languages a dictionary file will be required.
I totally support the idea to include HTML in a submission, but it is a regulatory agency which we need to make this decision. Currently their expectation is to receive XML + XSL. I do not remember if we asked CDER about it, if not I can write them a proposal, but we will also need to get in touch with PMDA and NMPA, which might be a bit more complicated. I think I know whom to write in NMPA, for PMDA I have an address as well, but once I used it and was told that this is not a valid e-mail for questions.

**Comment by lexjansen** [comment]
Yes, it would be great if you want to ask.

**Comment by lexjansen** [comment]
The approach mentioned in this thread has been implemented.
