### ISSUE TITLE
html language

### ISSUE THREAD

**Issue by tomhub** [lexjansen/define-xml-2.0-stylesheets#4]
Hi Lex,

I think the localization/html/ outputs need dynamic setup of lang="XX": at the moment all examples have
`<html lang="en">`
For Japanese, I expected:
`<html lang="ja">` [1]
For Chinese:
`<html lang="zh">` [1]

Chinese (Simplified)
`<html lang="zh-Hans">` [2]
Chinese (Traditional):
`<html lang="zh-Hant">` [2]

I think it would also be better to refer Japanese to 'ja' rather than 'jp'. [3]

Language codelists taken from:
[1] https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
[2] https://www.w3schools.com/tags/ref_language_codes.asp
[3] https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=ja

**Comment by lexjansen** [comment]
Thanks, Tomas, good points.
I will update.

**Comment by lexjansen** [comment]
I have updated this.
