### ISSUE TITLE
Decoded value in VLM with comparator matching multiple values

### ISSUE THREAD

**Issue by tomhub** [lexjansen/define-xml-2.0-stylesheets#5]
Hi Lex,

I would like to know if the stylesheet behaviour is expected:
1. Variable `X` has integer values: `1, 2, 3, 1001, 1002, .., 1010`. Decodes are as followed:
`1: a1`
`2: a2`
`3: a3`
`1001: b1`
`1002: b2`
`...`
`1010: b10`

2. Variable `Y` defined using VLM:
`Y = y1, where X EQ 1`
`Y = y2, where X EQ 2`
`Y = y3, where X GE 3`

In the output VLM where conditions are formatted with decodes as such:
`X = 1 (a1)`
`X = 2 (a2)`
`X ≥ 3 (a3)`

I agree that decodes are correct for conditions using EQ comparator. However, the decode (in `X ≥ 3 (a3)`) seems to be misleading, as the condition covers >1 value, and should have multiple decodes. I think the possible solutions would be: not to display decode at all where where condition match multiple values, or to display all matched decodes, or to link to the table of code - decoded.

I think LE comparator should be treated in the manner.

**Comment by DmitryMK** [comment]
That sounds logical, still I can easily imagine a situation where a decode will make sense as well.
For example, you can have the following codelist:

Code | Decode
------------ | -------------
1|Mild
2|Moderate
3|Severe

So a decode in condition `ASEV > 2 (Moderate)` might actually help to understand it. 

In general I see quite a few cases when operators other than EQ, NE, IN, NOTIN are used. I see usage of GE,LE,GT,LT mostly in ARM, but it never actually caught my eye, when a decode was used in them.

**Comment by tomhub** [comment]
The example you provide makes sense, but I have an example, where the greater integer values doesn't have related meaning to the lower integer decode value.  eg. in time to event dataset, decodes of censoring values 1,2,3 aren't related, and displaying just one of them might be misleading:
|Code|Decode|
| :------------- | :----------|
|1|Death|
|2|Lost to follow-up|
|3|Completed treatment without event|

In addition, I just checked that comparators GT and LT are also affected.

**Comment by tomhub** [comment]
On a further note, my proposal would be to populate decode value in where conditions with LT, LE, GE, and GT when the codelist CodedValue and Rank have the same values. I think, in such case it would enable define.xml author to control the display of decode values in the where conditions with the aforementioned comparators. As per example above of ASEVN, the define.xml with rank as below would display decode in where condition `ASEVN  ≥ 2 (Moderate)`:

|CodedValue|Decode|Rank|
|----|----|----|
|1|Mild|1|
|2|Moderate|2|
|3|Severe|3|

**Comment by lexjansen** [comment]
The only reason for displaying the decoded value was to make the WhereClause more readable when the coded value by itself is not that easy to understand for a reviewer. It was not the intent to derive which values are actually included in the WhereClause and then display their decodes.
Also, there is no expectation that Rank has consecutive integers. I am very hesitant to try to interpret values in the stylesheet.
I would see no fundamental difference in meaning between these 2 tables with metadata, but would be very hesitant to use LT, LE, GE, or GT, as that would really relate to the Rank, not the Codes or Decodes:

| CodedValue  | Decode | Rank |
| ------------- | ------------- |--- |
| 1 | Mild  |1|
| 2 | Moderate |2|
| 3 | Severe |3 |

and 

| CodedValue  | Decode | Rank |
| ------------- | ------------- |--- |
| 1 | Mild  |10|
| 2 | Moderate |20|
| 3 | Severe |30 |

I feel that LT, LE, GE, or GT really make most sense for quantitative data, not so much categorical data. 

Btw, it is interesting to me that we defined Rank as an integer in Define-XML. In ODM it is a float. Actually, decimals (1.1, 1.2, etc.) could make sense to me.

**Comment by tomhub** [comment]
> The only reason for displaying the decoded value was to make the WhereClause more readable when the coded value by itself is not that easy to understand for a reviewer. It was not the intent to derive which values are actually included in the WhereClause and then display their decodes.

I think this makes sense - I was looking at it as a set of selected decodes by the WhereClause.
