### ISSUE TITLE
New line symbols (CR/LF) are not respected

### ISSUE THREAD

**Issue by tomhub** [lexjansen/define-xml-2.0-stylesheets#8]
Hi

Based on my experience, most of the time specifications are written in excel, with list items being added in the same cell, on new line. Ex;
```TEXT
Map values:
'something' to 'Normal'
'else' to 'Abnormal'
```
etc.
So in HTML, everything is displayed ignoring line-breaks:
```TEXT
Map values: 'something' to 'Normal' 'else' to 'Abnormal'
```
Usually these line breaks enhance readability. Therefore, I think it would be nice to have an stylesheet option which would allow to enable the output to respect break-lines.

In fop, it would be something like this to preserve line-breaks:
```XML
<fo:block linefeed-treatment="preserve">line 1
line 2</fo:block>
```

**Comment by tomhub** [comment]
My bad. I think this is already implemented, but not every browser honors html style options. The same define.xml + define2-0-0.xsl is shown differently across different browsers, versions, ex. IE11 did not preserve line breaks, but the same define.xml has new lines preserved when viewed in IE of Windows Server 2019 Standard.

**Comment by DmitryMK** [comment]
I believe the current version shows line breaks for methods and does not show it for comments. It is controlled by `white-space: pre-wrap;` in the **.method-code** selector. The comment is controlled by **.description** selector and does not have this property.
