### ISSUE TITLE
Stylesheet does not display decodes in WhereClause

### ISSUE THREAD

**Issue by lexjansen** [lexjansen/define-xml-2.0-stylesheets#9]
[1642596341661.pdf](https://github.com/lexjansen/define-xml-2.0-stylesheets/files/8018416/1642596341661.pdf)

When variables in a WhereClause (like PARAMCD) have the Codelists in VLM, we lose the ability from the stylesheet to display the parameter codes with their associated parameter name between parentheses in the where clause cells.
The issue is that the stylesheet is looking for the PARAM and PARAMCD controlled terminologies as if the controlled terminologies reference were at variable level rather than at VLM level.
PLease update the stylesheet so it looks for controlled terminology reference at VLM level first and if it doesn’t exists then at variable level.

**Comment by dostiep** [comment]
I updated the stylesheet accordingly. Please see attached.
[define2-0-0.txt](https://github.com/lexjansen/define-xml-2.0-stylesheets/files/10675061/define2-0-0.txt)

**Comment by lexjansen** [comment]
Thanks, Pierre! I will make this available ASAP in 2.0 and 2.1.

**Comment by lexjansen** [comment]
@dostiep I added the fix  to the issues/09_decodes_in_whereclause branch.
2 notes:
- I fixed a small regression issue that happened when a variable in a whereclause does not have a codelist (unlikely, but possible)
- I kept the selection criteria in ARM without decodes, as it resembles a programming where statement

I added a testfile localization/xml/define.cdisc.adam_issue09.xml that converts as expected.

Do you like to review? If not or when there is no issue,  I will merge to master.

**Comment by dostiep** [comment]
Thanks Lex, I fully trust you on that. No need to review. Let me know when it's merged to master and I'll download the new version. 
For the second bullet point, I think I had set it to display the decodes to see if it was working but forgot to set it back to the original value.

**Comment by lexjansen** [comment]
This issues has been completed.
The issue branch has been merged with the master branch.
